AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: TypeScript Lambda Project

Globals:
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'Content-Type, X-Amz-Date, Authorization, X-Api-Key, x-requested-with'"
      AllowOrigin: "'*'"
  Function:
    Layers:
      - !Ref RuntimeDependenciesLayer

Resources:
  RuntimeDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: makefile
      BuildArchitecture: x86_64
    Properties:
      Description: Runtime dependencies for Lambdas
      ContentUri: dist/
      CompatibleRuntimes:
        - nodejs20.x
      RetentionPolicy: Delete

  UtilsFunctionLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: makefile
      BuildArchitecture: x86_64
    Properties:
      Description: Common layer
      ContentUri: dist/
      CompatibleRuntimes:
        - nodejs20.x
      RetentionPolicy: Delete

  FaasFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/lambdas/faas/
      Handler: faas.lambdaHandler
      Runtime: nodejs20.x
      Layers:
        - !Ref UtilsFunctionLayer
      Architectures:
        - x86_64
      Events:
        Base:
          Type: Api
          Properties:
            Path: /faas/
            Method: any
        Others:
          Type: Api
          Properties:
            Method: any
            Path: /faas/{proxy+}
